Merged TXT removal branch back to trunk. * TXT save engine is removed and no longer supported. * See also tid:53926, tid:57717.
git-svn-id: https://svn.code.sf.net/p/rathena/svn/trunk@15503 54d463be-8e91-2dee-dedb-b68131a5f0ec

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -868,9 +868,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-mysql[=ARG]
-                          use MySQL client library, optionally specify the
-                          path to the mysql_config executable (by default
-                          mysql is used if found)
+                          optionally specify the path to the mysql_config
+                          executable
   --with-MYSQL_CFLAGS=ARG specify MYSQL_CFLAGS manually (instead of using
                           "mysql_config --include")
   --with-MYSQL_LIBS=ARG   specify MYSQL_LIBS manually (instead of using
@@ -1339,8 +1338,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
                     ac_config_files="$ac_config_files src/char/Makefile src/login/Makefile"
 
-                    ac_config_files="$ac_config_files src/char_sql/Makefile src/txt-converter/Makefile"
-
                               ac_config_files="$ac_config_files src/map/Makefile src/plugins/Makefile src/tool/Makefile"
 
 
@@ -1486,30 +1483,22 @@ fi;
 
 
 #
-# Enable/disable MySql and optionally specify the path to mysql_config (optional library)
+# Optionally specify the path to mysql_config
 #
 
 # Check whether --with-mysql or --without-mysql was given.
 if test "${with_mysql+set}" = set; then
   withval="$with_mysql"
 
-		if test "$withval" = "no" ; then
-			want_mysql="no"
-		else
-			want_mysql="yes"
-			require_mysql="yes"
-			if test "$withval" != "yes" ; then
-				if test ! -x "$withval" ; then
-					{ { echo "$as_me:$LINENO: error: $withval is not an executable file" >&5
+		if test "$withval" != "no" ; then
+			if test ! -x "$withval" ; then
+				{ { echo "$as_me:$LINENO: error: $withval is not an executable file" >&5
 echo "$as_me: error: $withval is not an executable file" >&2;}
    { (exit 1); exit 1; }; }
-				fi
-				MYSQL_CONFIG_HOME="$withval"
 			fi
+			MYSQL_CONFIG_HOME="$withval"
 		fi
 
-else
-  want_mysql="yes" require_mysql="no"
 
 fi;
 
@@ -5096,18 +5085,11 @@ fi
 
 
 #
-# MySQL library (optional)
+# MySQL library
 #
 
-if test "$want_mysql" = "no" ; then
-	MYSQL_VERSION=""
-	MYSQL_CFLAGS=""
-	MYSQL_LIBS=""
-	{ echo "$as_me:$LINENO: ignoring MySQL (optional)" >&5
-echo "$as_me: ignoring MySQL (optional)" >&6;}
-else
-	if test -z "$MYSQL_CONFIG_HOME"; then
-		# Extract the first word of "mysql_config", so it can be a program name with args.
+if test -z "$MYSQL_CONFIG_HOME"; then
+	# Extract the first word of "mysql_config", so it can be a program name with args.
 set dummy mysql_config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -5147,23 +5129,23 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-	fi
+fi
 
-	if test "$MYSQL_CONFIG_HOME" != "no" ; then
-		MYSQL_VERSION="`$MYSQL_CONFIG_HOME --version`"
-		if test "$manual_MYSQL_CFLAGS" = "no" ; then
-			MYSQL_CFLAGS="`$MYSQL_CONFIG_HOME --include`"
-		fi
-		if test "$manual_MYSQL_LIBS" = "no" ; then
-			MYSQL_LIBS="`$MYSQL_CONFIG_HOME --libs`"
-		fi
-	else
-		MYSQL_VERSION="unknown"
+if test "$MYSQL_CONFIG_HOME" != "no" ; then
+	MYSQL_VERSION="`$MYSQL_CONFIG_HOME --version`"
+	if test "$manual_MYSQL_CFLAGS" = "no" ; then
+		MYSQL_CFLAGS="`$MYSQL_CONFIG_HOME --include`"
 	fi
+	if test "$manual_MYSQL_LIBS" = "no" ; then
+		MYSQL_LIBS="`$MYSQL_CONFIG_HOME --libs`"
+	fi
+else
+	MYSQL_VERSION="unknown"
+fi
 
-	MYSQL_OLD_LDFLAGS="$LDFLAGS" ; LDFLAGS="$LDFLAGS $MYSQL_LIBS"
-	MYSQL_OLD_CPPFLAGS="$CPPFLAGS" ; CPPFLAGS="$CPPFLAGS $MYSQL_CFLAGS"
-	echo "$as_me:$LINENO: checking for mysql_init in -lmysqlclient" >&5
+MYSQL_OLD_LDFLAGS="$LDFLAGS" ; LDFLAGS="$LDFLAGS $MYSQL_LIBS"
+MYSQL_OLD_CPPFLAGS="$CPPFLAGS" ; CPPFLAGS="$CPPFLAGS $MYSQL_CFLAGS"
+echo "$as_me:$LINENO: checking for mysql_init in -lmysqlclient" >&5
 echo $ECHO_N "checking for mysql_init in -lmysqlclient... $ECHO_C" >&6
 if test "${ac_cv_lib_mysqlclient_mysql_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -5231,7 +5213,7 @@ if test $ac_cv_lib_mysqlclient_mysql_init = yes; then
   HAVE_MYSQL="yes"
 fi
 
-	if test "${ac_cv_header_mysql_h+set}" = set; then
+if test "${ac_cv_header_mysql_h+set}" = set; then
   echo "$as_me:$LINENO: checking for mysql.h" >&5
 echo $ECHO_N "checking for mysql.h... $ECHO_C" >&6
 if test "${ac_cv_header_mysql_h+set}" = set; then
@@ -5375,29 +5357,20 @@ else
 fi
 
 
-	CPPFLAGS="$MYSQL_OLD_CPPFLAGS"
-	LDFLAGS="$MYSQL_OLD_LDFLAGS"
+CPPFLAGS="$MYSQL_OLD_CPPFLAGS"
+LDFLAGS="$MYSQL_OLD_LDFLAGS"
 
-	echo "$as_me:$LINENO: checking MySQL library (optional)" >&5
-echo $ECHO_N "checking MySQL library (optional)... $ECHO_C" >&6
-	if test "$HAVE_MYSQL" = "yes" ; then
-		echo "$as_me:$LINENO: result: yes ($MYSQL_VERSION)" >&5
+echo "$as_me:$LINENO: checking MySQL library (required)" >&5
+echo $ECHO_N "checking MySQL library (required)... $ECHO_C" >&6
+if test "$HAVE_MYSQL" = "yes" ; then
+	echo "$as_me:$LINENO: result: yes ($MYSQL_VERSION)" >&5
 echo "${ECHO_T}yes ($MYSQL_VERSION)" >&6
-	else
-		echo "$as_me:$LINENO: result: no" >&5
+else
+	echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-		if test "$require_mysql" = "yes" ; then
-			{ { echo "$as_me:$LINENO: error: MySQL not found or incompatible (requested)" >&5
-echo "$as_me: error: MySQL not found or incompatible (requested)" >&2;}
+	{ { echo "$as_me:$LINENO: error: MySQL not found or incompatible" >&5
+echo "$as_me: error: MySQL not found or incompatible" >&2;}
    { (exit 1); exit 1; }; }
-		else
-			{ echo "$as_me:$LINENO: disabling MySQL (optional)" >&5
-echo "$as_me: disabling MySQL (optional)" >&6;}
-			MYSQL_VERSION=""
-			MYSQL_CFLAGS=""
-			MYSQL_LIBS=""
-		fi
-	fi
 fi
 
 
@@ -6195,8 +6168,6 @@ do
   "3rdparty/mt19937ar/Makefile" ) CONFIG_FILES="$CONFIG_FILES 3rdparty/mt19937ar/Makefile" ;;
   "src/char/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/char/Makefile" ;;
   "src/login/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/login/Makefile" ;;
-  "src/char_sql/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/char_sql/Makefile" ;;
-  "src/txt-converter/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/txt-converter/Makefile" ;;
   "src/map/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/map/Makefile" ;;
   "src/plugins/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/plugins/Makefile" ;;
   "src/tool/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/tool/Makefile" ;;
